[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true



remappings=[
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@anon-aadhaar/=lib/anon-aadhaar/packages/"
]

eth_rpc_url = "https://base-sepolia.g.alchemy.com/v2/kBfhfjgaUbr1xz7I4QTPU7ZepOM6uMxK"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
